### ISSUE TITLE
SAM_Molmo_Whisper requirements.txt out of sync with SAM2 requirements

### ISSUE THREAD

**Issue by medatasci** [sovit-123/SAM_Molmo_Whisper#8]
Any chance requirements.txt could be updated?
Because SAM2 was updated after SAM_Molmo_Whisper there are some versioning problems with torch*.
When installing on a fresh machine, I'm getting version conflicts with torchaudio leading to errors like this:
Thanks.

```
Traceback (most recent call last):
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/gradio/queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/gradio/blocks.py", line 2014, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/SAM_Molmo_Whisper/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/root/verb-workspace/SAM_Molmo_Whisper2/SAM_Molmo_Whisper/./app.py", line 92, in process_image
    transcribed_text, prompt = get_whisper_output(audio, transcriber)
  File "/root/verb-workspace/SAM_Molmo_Whisper2/SAM_Molmo_Whisper/utils/model_utils.py", line 76, in get_whisper_output
    sr, y = audio
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by sovit-123** [comment]
@medatasci, I will check and update you here..

**Comment by sovit-123** [comment]
@medatasci Can you please let me know what version of PyTorch you are using?
I just went through the SAM2 repo and saw that the minimum version has been updated from 2.4 to 2.5 now. I will see to the issues and push an update as soon as possible.

**Comment by sovit-123** [comment]
@medatasci An update. 
I checked that the recent changes had requirement issues. I have updated all requirements to match SAM2. Please install everything in a new conda environment with Python >= 3.10. It should work.

I am closing the issue for now. Please re-open if you face issues.

**Comment by medatasci** [comment]
Thanks for the really prompt bug fix, much appreciated.
Images are working well.

I had some trouble with videos and submitted a new issue.  Could it be caused an updated SAM2 API?

Marc

**Comment by sovit-123** [comment]
Hi. I have given an initial reply in the video processing issue that you created. Let's continue the conversation there.
